### ISSUE TITLE
eyephish fails to locate font files on ubuntu

### ISSUE THREAD

**Issue by thesle3p** [phar/eyephish#2]
It looks like eyephish is failing to locate the font files it needs to generate domain names. Bellow is the syntax and output provided, I tried both by manually specifying font types and with out:

```
python eyephish.py --inputstring "microsoft" --dialect=cyrillic --font Arial
Traceback (most recent call last):
  File "eyephish.py", line 104, in <module>
    im1 = get_centroidized_unicode_img(i,args.font)
  File "eyephish.py", line 43, in get_centroidized_unicode_img
    ttf=ImageFont.truetype(font, fontsize)
  File "/usr/lib/python2.7/dist-packages/PIL/ImageFont.py", line 239, in truetype
    return FreeTypeFont(font, size, index, encoding)
  File "/usr/lib/python2.7/dist-packages/PIL/ImageFont.py", line 128, in __init__
    self.font = core.getfont
```

**Comment by phar** [comment]
If the fonts are not in your path you can specify the full path to the _ttf_ font, but you'll need to make sure its one of the full unicode fonts such as tahoma or arial:
`$ python eyephish.py --inputstring "microsoft" --dialect=cyrillic --font=/Library/Fonts/Arial.ttf`
